# All code below added by Cibin

alias cleawr='clear'
alias del='trash-put'
alias mosh='mosh --no-init'
alias iv='vi'
alias octave='octave --no-gui'
alias rclone-pull='timesync && rclone copy -u -L -P --drive-skip-gdocs GoogleDrive: /home/cibin/Google_Drive'
alias rclone-pull-sync='timesync && rclone sync -u -L -P --drive-skip-gdocs GoogleDrive: /home/cibin/Google_Drive'
alias rclone-pull-dry='timesync && rclone copy -u -L -P --drive-skip-gdocs --dry-run GoogleDrive: /home/cibin/Google_Drive'
alias rclone-push='timesync && rclone copy -u -L -P --drive-skip-gdocs /home/cibin/Google_Drive GoogleDrive:'
alias rclone-push-sync='timesync && rclone sync -u -L -P --drive-skip-gdocs /home/cibin/Google_Drive GoogleDrive:'
alias rclone-push-dry='timesync && rclone copy -u -L -P --drive-skip-gdocs --dry-run /home/cibin/Google_Drive GoogleDrive:'
alias rclone-bisync='timesync && rclone bisync --drive-skip-gdocs /home/cibin/Google_Drive GoogleDrive:'
alias rclone-bisync-dry='timesync && rclone bisync --drive-skip-gdocs --dry-run /home/cibin/Google_Drive GoogleDrive:'
alias gsync='rclone-bisync'
alias gsync-dry='rclone-bisync-dry'
alias sl='ls'
alias au='sudo apt update && sudo apt upgrade -y && sudo apt autoremove && sudo apt autoclean'
alias rm='/bin/safe-rm'
alias openvsp='vsp'
alias tecplot='tec360'
alias vpn='sudo openfortivpn -c ~/.config/openfortivpn/config'
alias gripu='grip --user=cibinjoseph'
alias meld='flatpak run org.gnome.meld'
alias mendeley='/opt/mendeley-reference-manager.AppImage'
alias dc="cd"
alias julia-project="julia --project=."


# Git aliases
git config --global alias.ch checkout
git config --global alias.br branch
git config --global alias.co commit
git config --global alias.st status

# for auto ls after cd
function cd {
  builtin cd "$@" && ls
}

# for printing header of files
function header {
 head -n 1 "$@"
}

# Color for fortran and python files 
LS_COLORS="$LS_COLORS:*.f90=0;36:*.py=0;32:*.jl=0;36"

timesync() {
  sudo date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"
}

# Command for clearing additional files generated by texstudio
texclear() {
  echo 'Clearing files:'
  ls *.aux *log *.glo *.glsdefs *.nlo *.acn *.dvi *.nlg *.snm *.bbl *.lof *.lot *.blg *.nav *.out *.synctex.gz *.toc 2>/dev/null
  trash-put *.aux *log *.glo *.glsdefs *.nlo *.acn *.dvi *.nlg *.snm *.bbl *.lof *.lot *.blg *.nav *.out *.synctex.gz *.toc 2>/dev/null
}

# Cmmand for swapping files
fileswap() {
  local TMPFILE=tmp.$$
  mv "$1" $TMPFILE && mv "$2" "$1" && mv $TMPFILE "$2"
}

# untar command
function untar {
  tar -xvf "$@"
}

# labsync command
function labsync {
  rsync -rvRP lab:$(readlink -f $1) /
}

# Copy pwd from a terminal
alias c="pwd | xclip -selection clipboard"
